@startuml
Identifier : # value: String

Catch : # exception: Property

Loop : # evaluations: List<Expression>

Conditional : # ifExpr: Expression
Conditional : # elseIfExpr: List<Expression>
Conditional : # elseExpr: Expression

LogicalSequence : # operands: List<Expression>

Jump : # label: String?

Lambda : # parameters: List<Property>

UnitCall : # reference: Expression
UnitCall : # arguments: List<Expression>

Declaration : # value: Scope

Assignment : # reference: Expression

@enduml