@startuml
class Loop
class Conditional
class LogicalSequence
class Jump
class LocalDeclaration
class Assignment
class Lambda
class UnitCall

Identifier : # value: String

Catch : # exception: Property

Loop : # evaluations: List<Expression>

Conditional : # ifExpr: Expression
Conditional : # elseIfExpr: List<Expression>
Conditional : # elseExpr: Expression

LogicalSequence : # operands: List<Expression>

Jump : # label: String?

Lambda : # parameters: List<Property>

UnitCall : # reference: Expression
UnitCall : # arguments: List<Expression>

LocalDeclaration : # declaration: Declarable

Assignment : # reference: Expression
Assignment : # value: Expression?

Switch : # subject: Expression?
Switch "1" *-- "*" SwitchCase : cases >

SwitchCase : # pattern: Expression?

@enduml