@startuml
skinparam dpi 300

class ModuleRoot
class Module
abstract class Declarable
abstract class SourceElement

enum ModuleType {
    CLASS
    ENUM
    INTERFACE
    RECORD
}

enum ModifierType {
    PUBLIC
    PROTECTED
    PRIVATE
    STATIC
    FINAL
    ABSTRACT
    OVERRIDE
}

ModuleRoot : # filePath: String
ModuleRoot : # fileName: String
ModuleRoot : # componentName: String?
ModuleRoot : # imports: List<String>
ModuleRoot *-- Module: # module >

SourceElement : # metadata: Metadata

SourceElement <|-- Declarable
SourceElement <|-- Expression

Declarable : # id: String
Declarable : # returnType : String?
Declarable *-- "*" ModifierType : modifiers >

Declarable <|-- Module
Declarable <|-- Unit
Declarable <|-- Property

Module : # extends: List<String>
Module : # implements: List<String>
Module : # members: List<Declarable>
Module *-- ModuleType : moduleType >

Unit : # parameters: List<Property>
Unit : # body: Expression?

Property : # initializer: Expression?

Expression : # context: String?
Expression : # innerScope: List<SourceElement>

@enduml